// ✅ Updated main content area for independent scrolling – 2025-01-27 (by Cursor AI)
// ✅ Added Toaster component for toast notifications – 2025-01-27 (by Cursor AI)
// ✅ Fixed overflow-hidden to allow zoom overlay to appear above all UI – 2025-01-27 (by Cursor AI)

import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
// import { StagewiseToolbar } from "@stagewise/toolbar-next"
import { Toaster } from "@/components/ui/toaster"
import { AuthProvider } from "@/contexts/AuthContext"
import { LayoutWrapper } from "@/components/LayoutWrapper"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <AuthProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </AuthProvider>
        {/* <StagewiseToolbar /> */}
        <Toaster />
      </body>
    </html>
  )
}